name: Module Test

on: 
  push:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: 
          - "3.10" 
          - "3.11"
          - "3.12"
        
    name: Test
    runs-on:  ${{ matrix.os }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install module
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pytest setuptools>=42.0.0
          pip3 install .
          
      - name: Install module
        run: |         
          python3 tests/install_tf.py
          pip3 install numpy torch pandas --no-deps

      - name: Run Test
        run: pytest 